root = "/workspace"
tmp_dir = "/tmp/navire-dspc-air"

[build]
cmd = "go build -buildvcs=false -o ./bin/navire-dispatcher ./cmd/dispatcher"
bin = "./bin/navire-dispatcher"
include_ext = ["go"]
exclude_dir = ["bin", "tmp", ".git", "coverage.html"]
delay = 500
stop_on_error = true
